apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - release.yaml
  - source.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml
