# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
deployment:
  terminationGracePeriodSeconds: 60
ingressClass:
  enabled: true
  name: traefik
gateway:
  enabled: false
gatewayClass:
  enabled: false
api:
  dashboard: true
  debug: true
  disabledashboardad: true
  basePath: /traefik
  insecure: true
updateStrategy:
  type: Recreate
providers:
  kubernetesIngress:
    enabled: true
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
service:
  type: NodePort
ports:
  web:
    port: 80
    hostPort: 80
    containerPort: 80
  websecure:
    port: 443
    hostPort: 443
    containerPort: 443
  metrics:
    port: 9111
#   nodeSelector:
#     kubernetes.io/os: linux
#   tolerations:
#     - effect: NoSchedule
#       key: node-role.kubernetes.io/master
#       operator: Equal
#     - effect: NoSchedule
#       key: node-role.kubernetes.io/control-plane
#       operator: Equal
metrics:
  prometheus:
    serviceMonitor:
      enabled: true
      namespace: monitoring
logs:
  general:
    level: "DEBUG"
